Add optional filter level param to set log stream
breez/breez-sdk-rn-generator pull request #23
Opened 2024-03-22 11:46 UTC by erdemyerebasmaz

`setLogStream` and `connect` aren't generated in the same way as the other methods and needs to be updated manually.

Changes required for: 
- https://github.com/breez/breez-sdk/pull/874

2024-03-22 12:18 UTC, dangeross reviewed
You also need to change the implementation in the native generators

Kotlin:
https://github.com/breez/breez-sdk-rn-generator/blob/59b4ba2a92bca5c2cb83f42d44f8a28583bd6566/src/gen_kotlin/templates/module.kt#L65

Swift:
https://github.com/breez/breez-sdk-rn-generator/blob/59b4ba2a92bca5c2cb83f42d44f8a28583bd6566/src/gen_swift/templates/extern.m#L11
https://github.com/breez/breez-sdk-rn-generator/blob/59b4ba2a92bca5c2cb83f42d44f8a28583bd6566/src/gen_swift/templates/module.swift#L75-L76

2024-03-22 17:23 UTC, dangeross commented on src/gen_swift/templates/module.swift
>      @objc(setLogStream:reject:)
```suggestion
    @objc(setLogStream:resolve:reject:)
```

2024-03-22 17:23 UTC, dangeross commented on src/gen_swift/templates/module.swift
> +    func setLogStream(_ filterLevel: LevelFilter = nil, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
React Native only likes basic types going over the bridge between native & javascript. So we should change this to an optional String, then convert it.
```suggestion
    func setLogStream(_ filterLevel: String?, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
```

2024-03-22 17:23 UTC, dangeross commented on src/gen_swift/templates/module.swift
> +            try BreezSDK.setLogStream(logStream: BreezSDKLogStream(), filterLevel: filterLevel)
Convert the optional param
```suggestion
            var levelFilter: LevelFilter? = nil
            if filterLevel != nil {
                levelFilter = try BreezSDKMapper.asLevelFilter(levelFilter: filterLevel!)
            }
            try BreezSDK.setLogStream(logStream: BreezSDKLogStream(), filterLevel: levelFilter)
```

2024-03-22 17:23 UTC, dangeross commented on src/gen_kotlin/templates/module.kt
> +    fun setLogStream(filterLevel: String, promise: Promise) {
I think this should be optional
```suggestion
    fun setLogStream(filterLevel: String?, promise: Promise) {

```

2024-03-22 17:23 UTC, dangeross commented on src/gen_kotlin/templates/module.kt
> +                val levelFilter = asLevelFilter(filterLevel);
and then converted if set
```suggestion
                val levelFilter = filterLevel?.let { asLevelFilter(filterLevel) }
```

2024-03-24 17:18 UTC, dangeross requested changes
Looks good, but please bump the Cargo.toml version

2024-03-25 06:59 UTC, erdemyerebasmaz commented
> Looks good, but please bump the Cargo.toml version

Bumped 430a73ab27a70e2dfdb70fac7797d213ba6138aa 👍

2025-05-17 08:29 UTC, closed without merging